version: '2'

services:
  database:
    image: postgres
    container_name: rpg
    restart: always
    ports: -'5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rpg
    volumes: -'pgdata:/data/postgres'

volumes:
  pgdata:
    driver: local
